# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "translated_attr"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matteo Canato"]
  s.date = "2012-04-27"
  s.description = "A minimal translation library for translating database values for Rails 3.x"
  s.email = "mcanato@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.rdoc",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "TODO.rdoc",
    "VERSION",
    "init.rb",
    "lib/translated_attr.rb",
    "lib/translated_attr/active_record_extensions.rb",
    "lib/translated_attr/version.rb",
    "translated_attr.gemspec"
  ]
  s.homepage = "http://github.com/mcanato/translated_attr"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "A minimal translation library for translating database values for Rails 3.x"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

